# Generated by Django 5.2.5 on 2025-08-11 02:34

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="lnglat",
            field=models.CharField(
                blank=True,
                help_text="경도, 위도 포맷",
                max_length=100,
                null=True,
                validators=[blog.models.lnglat_validator],
                verbose_name="경,위도",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="region",
            field=models.CharField(
                choices=[
                    ("Europe", "유럽"),
                    ("Asia", "아시아"),
                    ("Oceania", "오세아니아"),
                    ("America", "아메리카"),
                ],
                default="Asia",
                max_length=20,
                verbose_name="지역",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(
                help_text="기사 제목입니다. 100자 내외", max_length=100, verbose_name="제목"
            ),
        ),
    ]
