/*
[제출 파일]
ERD 캡처한 png파일(exERD.png)과  sql 작성 파일
[요구사항]
(1) 같은 이름의 테이블이나 시퀀스가 있을 수 있으니 먼저 삭제하고 테이블을 생성하시오
(2) MEMBER 테이블은 필드 별로 다음의 조건을 지켜 생성하시오.
	① mNO(번호) : 주키
	② mNAME(이름) : NULL값을 입력할 수 없다
	③ mPW(비밀번호) : 반드시 1~8글자 이내의 문자를 입력한다
	④ mEMAIL(메일) : 모든 데이터는 EMAIL 필드값이 모두 다르게 입력된다.
	⑤ mPOINT(포인트) : 0이상의 값만 입력할 수 있다.
	⑥ mRDATE(가입일) : 입력하지 않을 시, 기본적으로 현재날짜로 입력된다.
⑦ LEVELNO : MEMBER_LEVEL 테이블의 LEVELNO 필드를 참조하는 외래키
(3) MEMBER_LEVEL 테이블은 필드 별로 다음의 제약조건을 지킨다.
	① LEVELNO : 주키
	② LEVELNAME : NULL값을 입력할 수 없다	
(4) MEMBER 테이블의 mNO번호는 시퀀스(MEMBER_MNO_SQ)를 생성한 뒤 자동생성 번호로 입력

*/

-- (1) 테이블 생성
DROP TABLE MEMBER_LEVEL;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(2),
    LEVELNAME VARCHAR2(20) NOT NULL,
    PRIMARY KEY (LEVELNO)
);

DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    MNO NUMBER(2),
    MNAME VARCHAR2(20) NOT NULL,
    MPW VARCHAR2(10) CHECK(LENGTH(MPW) BETWEEN 1 AND 8),
    MMAIL VARCHAR2(50) UNIQUE,
    MPOINT NUMBER(5) DEFAULT 0,
    MRDATE DATE DEFAULT SYSDATE,
    PRIMARY KEY(MNO),
    LEVELNO NUMBER(2) REFERENCES MEMBER_LEVEL(LEVELNO)    
);

--(2)시퀀스 생성
DROP SEQUENCE MEMBER_SQ;
CREATE SEQUENCE MEMBER_SQ
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 9
    MINVALUE 1
    NOCYCLE
    NOCACHE;

DROP SEQUENCE MEMBER_LEVEL_SQ;
CREATE SEQUENCE MEMBER_LEVEL_SQ
    START WITH -1
    INCREMENT BY 1
    MAXVALUE 9
    MINVALUE -1
    NOCYCLE
    NOCACHE;
    
-- INSERT INTO MEMBER_LEVEL
INSERT INTO MEMBER_LEVEL VALUES (MEMBER_LEVEL_SQ.NEXTVAL, 'black');
INSERT INTO MEMBER_LEVEL VALUES (MEMBER_LEVEL_SQ.NEXTVAL, '일반');
INSERT INTO MEMBER_LEVEL VALUES (MEMBER_LEVEL_SQ.NEXTVAL, '실버');
INSERT INTO MEMBER_LEVEL VALUES (MEMBER_LEVEL_SQ.NEXTVAL, '골드');
COMMIT;
SELECT * FROM MEMBER_LEVEL;

-- INSERT INTO MEMBER ~
INSERT INTO MEMBER (MNO, MNAME, MPW, MMAIL, MRDATE, LEVELNO)
    VALUES (MEMBER_SQ.NEXTVAL,'홍길동','aa','hong@hong.com',TO_DATE('24/09/26','YY/MM/DD'),0);
    
INSERT INTO MEMBER (MNO, MNAME, MPW, MMAIL, MPOINT,MRDATE, LEVELNO)
    VALUES (MEMBER_SQ.NEXTVAL,'신길동','bb','sin@sin.com',1000,TO_DATE('22/04/01','YY/MM/DD'),1);    
COMMIT;
SELECT * FROM MEMBER;

--홍길동 생년월일 변경 
UPDATE  MEMBER 
    SET MRDATE = '2022-03-10'
        WHERE MNAME='홍길동' ;
--JOIN    
SELECT M.MNO , MNAME, TO_CHAR(MRDATE, 'YYYY-MM-DD') MRDATE,M.MMAIL,M.MPOINT point,ML.LEVELNAME||'고객' LEVELNAME
    FROM MEMBER M, MEMBER_LEVEL ML 
    WHERE M.LEVELNO=ML.LEVELNO;

    