# Generated by Django 5.2.5 on 2025-08-24 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accident_project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccidentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accident_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=200)),
                ("a_plate", models.CharField(blank=True, max_length=50)),
                ("b_plate", models.CharField(blank=True, max_length=50)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accident_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-accident_date", "-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner", "accident_date", "a_plate", "b_plate"),
                        name="uniq_owner_accidentdate_plates",
                    )
                ],
            },
        ),
    ]
