# Generated by Django 5.2.5 on 2025-08-24 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accident_project", "0002_accidentrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="agreements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="a_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="b_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="incident_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="agreement",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
