DROP TABLE TODO;
CREATE TABLE TODO(
  ID NUMBER(4) PRIMARY KEY,
  CONTENTS VARCHAR2(256) NOT NULL,
  IS_DONE  NUMBER(1) DEFAULT 0
);

-- CREATE
INSERT INTO TODO (ID, CONTENTS, IS_DONE) VALUES (1, 'flask', 0);
INSERT INTO TODO (ID, CONTENTS, IS_DONE) VALUES (2, '프로젝트발표', 0);
INSERT INTO TODO (ID, CONTENTS, IS_DONE) VALUES (3, '포트폴리오작성', 0);

-- READ
SELECT * FROM TODO ORDER BY ID DESC;
SELECT * FROM TODO WHERE ID = 1;

-- UPDATE
UPDATE TODO SET CONTENTS='바꿀내용', IS_DONE=1 WHERE ID=1;

-- DELETE
--DELETE FROM TODO WHERE ID=2;

-- next_id
SELECT NVL(MAX(ID), 0)+1 FROM TODO;

COMMIT;