# Generated by Django 5.2.4 on 2025-08-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insurance_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="car_model_code",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="license_date",
        ),
        migrations.AddField(
            model_name="customuser",
            name="has_license",
            field=models.BooleanField(default=False, verbose_name="운전면허 보유 여부"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(blank=True, null=True, verbose_name="생년월일"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "남성"), ("F", "여성"), ("O", "기타")],
                max_length=1,
                null=True,
                verbose_name="성별",
            ),
        ),
    ]
