# Generated by Django 5.2.5 on 2025-08-14 01:16

import book.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bok",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="책제목")),
                (
                    "author",
                    models.CharField(
                        max_length=50,
                        validators=[book.models.min_length_3_validator],
                        verbose_name="글쓴이",
                    ),
                ),
                (
                    "publisher",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="출판사"
                    ),
                ),
                (
                    "sales",
                    models.IntegerField(
                        default=1000,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                        verbose_name="판매가",
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("publication_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-publication_date"],
                "unique_together": {("title", "author")},
            },
        ),
    ]
