# Generated by Django 5.2.5 on 2025-08-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Bok",
            new_name="Book",
        ),
    ]
