# Generated by Django 5.2.5 on 2025-08-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accident_project", "0003_agreement_owner_alter_agreement_a_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
