# Generated by Django 5.2.5 on 2025-08-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("incident_dt", models.CharField(blank=True, max_length=32)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("a_name", models.CharField(blank=True, max_length=64)),
                ("b_name", models.CharField(blank=True, max_length=64)),
                ("damages_raw", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
