# Generated by Django 5.2.5 on 2025-08-19 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="article",
            name="photo",
            field=models.ImageField(blank=True, upload_to="article/%Y/%m/%d"),
        ),
    ]
